# Generated by Django 6.0.2 on 2026-02-16 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_url', models.URLField(db_index=True, max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('scripts', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=dict)),
                ('video_analyses', models.JSONField(blank=True, default=list)),
                ('download_results', models.JSONField(blank=True, default=list)),
                ('scraped_data_summary', models.JSONField(blank=True, default=dict)),
                ('full_result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'pipeline_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='pipeline_jo_status_8651c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(db_index=True, max_length=64)),
                ('stage_order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pipeline_jobs.pipelinejob')),
            ],
            options={
                'db_table': 'pipeline_stage',
                'ordering': ['stage_order'],
                'unique_together': {('job', 'stage_name')},
            },
        ),
    ]
