# Generated by Django 6.0.2 on 2026-02-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='skip_apify',
            field=models.BooleanField(default=False),
        ),
    ]
